mod HANOI is
    protecting NAT-LIST .
    sorts Tower Hanoi .
    subsort Tower < Hanoi .

    op (_)[_] : Nat NatList -> Tower [ctor] .
    op empty : -> Hanoi [ctor] .
    op __ : Hanoi Hanoi -> Hanoi [ctor assoc comm id: empty] .
    
    vars S T D1 D2 : Nat . vars L1 L2 : NatList .
    crl [move] : (S) [L1 D1] (T) [L2 D2] => (S) [L1] (T) [L2 D2 D1]
        if D2 > D1 .
    rl [move] : (S) [L1 D1] (T) [nil] => (S) [L1] (T) [D1] .
endm